theme: jekyll-theme-minimal

title: Ernest Quintana
logo: /assets/img/profile.jpg
position: Postdoctoral Researcher
institution:
  name: TU Ilmenau
  url: https://www.tu-ilmenau.de/en/
  country: Germany

social:
  email: <script>x = 'ernest.quintana-aparicio'; y = 'tu.ilmenau.de'; document.write('<a href="mailto:' + x + '@' + y + '"><i class="fas fa-envelope"></i></a>');</script>
  github:
    username: ernestqt  
  linkedin:
    username: ernest-quintana-907926a4  

navigation:
  - <a href="#publications">Publications </a>  
  - <a href="#career--education">Career & Education</a>
  - <a href="#contact">Contact</a>

